name: "build-dcevm with push to master "
on:
  push:
    branches:
      - master

jobs:
  dcevm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15, windows-2016]
        javaToBuild: [jdk11u, jdk16u]
    steps:
    - uses: actions/checkout@v1
    - uses: TravaOpenJDK/build-dcevm@v1
      id: buildJDK
      with:
        impl: dcevm
        javaToBuild: ${{ matrix.javaToBuild}}
        dcevm_branch: 'dcevm11-jdk-11.0.11-adopt'
        dcevm_tag: 'dcevm-11.0.11+1'
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
  
